package com.zireck.projectk.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zireck.projectk.model.Food;
import com.zireck.projectk.model.Meal;
import com.zireck.projectk.model.User;

import com.zireck.projectk.model.FoodDao;
import com.zireck.projectk.model.MealDao;
import com.zireck.projectk.model.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodDaoConfig;
    private final DaoConfig mealDaoConfig;
    private final DaoConfig userDaoConfig;

    private final FoodDao foodDao;
    private final MealDao mealDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodDaoConfig = daoConfigMap.get(FoodDao.class).clone();
        foodDaoConfig.initIdentityScope(type);

        mealDaoConfig = daoConfigMap.get(MealDao.class).clone();
        mealDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        foodDao = new FoodDao(foodDaoConfig, this);
        mealDao = new MealDao(mealDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Food.class, foodDao);
        registerDao(Meal.class, mealDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        foodDaoConfig.getIdentityScope().clear();
        mealDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public FoodDao getFoodDao() {
        return foodDao;
    }

    public MealDao getMealDao() {
        return mealDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
