package com.zireck.projectk.model;

import com.zireck.projectk.model.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MEAL.
 */
public class Meal extends MealBase  {

    private Long id;
    /** Not-null value. */
    private java.util.Date date;
    private int mealtime;
    private int grams;
    private double calories;
    private double fats;
    private double carbohydrates;
    private double proteins;
    private long foodId;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient MealDao myDao;

    private Food food;
    private Long food__resolvedKey;


    public Meal() {
    }

    public Meal(Long id) {
        this.id = id;
    }

    public Meal(Long id, java.util.Date date, int mealtime, int grams, double calories, double fats, double carbohydrates, double proteins, long foodId) {
        this.id = id;
        this.date = date;
        this.mealtime = mealtime;
        this.grams = grams;
        this.calories = calories;
        this.fats = fats;
        this.carbohydrates = carbohydrates;
        this.proteins = proteins;
        this.foodId = foodId;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getMealDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public int getMealtime() {
        return mealtime;
    }

    public void setMealtime(int mealtime) {
        this.mealtime = mealtime;
    }

    public int getGrams() {
        return grams;
    }

    public void setGrams(int grams) {
        this.grams = grams;
    }

    public double getCalories() {
        return calories;
    }

    public void setCalories(double calories) {
        this.calories = calories;
    }

    public double getFats() {
        return fats;
    }

    public void setFats(double fats) {
        this.fats = fats;
    }

    public double getCarbohydrates() {
        return carbohydrates;
    }

    public void setCarbohydrates(double carbohydrates) {
        this.carbohydrates = carbohydrates;
    }

    public double getProteins() {
        return proteins;
    }

    public void setProteins(double proteins) {
        this.proteins = proteins;
    }

    public long getFoodId() {
        return foodId;
    }

    public void setFoodId(long foodId) {
        this.foodId = foodId;
    }

    /** To-one relationship, resolved on first access. */
    public Food getFood() {
        long __key = this.foodId;
        if (food__resolvedKey == null || !food__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            FoodDao targetDao = daoSession.getFoodDao();
            Food foodNew = targetDao.load(__key);
            synchronized (this) {
                food = foodNew;
            	food__resolvedKey = __key;
            }
        }
        return food;
    }

    public void setFood(Food food) {
        if (food == null) {
            throw new DaoException("To-one property 'foodId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.food = food;
            foodId = food.getId();
            food__resolvedKey = foodId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
