package com.zireck.projectk.data.entity;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zireck.projectk.data.entity.FoodEntity;
import com.zireck.projectk.data.entity.MealEntity;
import com.zireck.projectk.data.entity.UserEntity;

import com.zireck.projectk.data.entity.FoodEntityDao;
import com.zireck.projectk.data.entity.MealEntityDao;
import com.zireck.projectk.data.entity.UserEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig foodEntityDaoConfig;
    private final DaoConfig mealEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;

    private final FoodEntityDao foodEntityDao;
    private final MealEntityDao mealEntityDao;
    private final UserEntityDao userEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        foodEntityDaoConfig = daoConfigMap.get(FoodEntityDao.class).clone();
        foodEntityDaoConfig.initIdentityScope(type);

        mealEntityDaoConfig = daoConfigMap.get(MealEntityDao.class).clone();
        mealEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        foodEntityDao = new FoodEntityDao(foodEntityDaoConfig, this);
        mealEntityDao = new MealEntityDao(mealEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);

        registerDao(FoodEntity.class, foodEntityDao);
        registerDao(MealEntity.class, mealEntityDao);
        registerDao(UserEntity.class, userEntityDao);
    }
    
    public void clear() {
        foodEntityDaoConfig.getIdentityScope().clear();
        mealEntityDaoConfig.getIdentityScope().clear();
        userEntityDaoConfig.getIdentityScope().clear();
    }

    public FoodEntityDao getFoodEntityDao() {
        return foodEntityDao;
    }

    public MealEntityDao getMealEntityDao() {
        return mealEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

}
