package com.zireck.projectk.data.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FOOD_ENTITY.
 */
public class FoodEntity extends FoodEntityBase  {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String brand;
    private boolean isDrink;
    private double calories;
    private double fats;
    private double carbohydrates;
    private double proteins;
    private String picture;

    public FoodEntity() {
    }

    public FoodEntity(Long id) {
        this.id = id;
    }

    public FoodEntity(Long id, String name, String brand, boolean isDrink, double calories, double fats, double carbohydrates, double proteins, String picture) {
        this.id = id;
        this.name = name;
        this.brand = brand;
        this.isDrink = isDrink;
        this.calories = calories;
        this.fats = fats;
        this.carbohydrates = carbohydrates;
        this.proteins = proteins;
        this.picture = picture;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getBrand() {
        return brand;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    public boolean getIsDrink() {
        return isDrink;
    }

    public void setIsDrink(boolean isDrink) {
        this.isDrink = isDrink;
    }

    public double getCalories() {
        return calories;
    }

    public void setCalories(double calories) {
        this.calories = calories;
    }

    public double getFats() {
        return fats;
    }

    public void setFats(double fats) {
        this.fats = fats;
    }

    public double getCarbohydrates() {
        return carbohydrates;
    }

    public void setCarbohydrates(double carbohydrates) {
        this.carbohydrates = carbohydrates;
    }

    public double getProteins() {
        return proteins;
    }

    public void setProteins(double proteins) {
        this.proteins = proteins;
    }

    public String getPicture() {
        return picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

}
