package com.zireck.projectk.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User extends UserBase  {

    private String name;
    private int gender;
    /** Not-null value. */
    private java.util.Date birthday;
    private Integer age;
    private int measurementSystem;
    private double weight;
    private int height;
    private int activityFactor;
    private Double bmr;
    private int goal;
    private Double maintain;
    private Double burn;
    private Double gain;

    public User() {
    }

    public User(String name, int gender, java.util.Date birthday, Integer age, int measurementSystem, double weight, int height, int activityFactor, Double bmr, int goal, Double maintain, Double burn, Double gain) {
        this.name = name;
        this.gender = gender;
        this.birthday = birthday;
        this.age = age;
        this.measurementSystem = measurementSystem;
        this.weight = weight;
        this.height = height;
        this.activityFactor = activityFactor;
        this.bmr = bmr;
        this.goal = goal;
        this.maintain = maintain;
        this.burn = burn;
        this.gain = gain;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getGender() {
        return gender;
    }

    public void setGender(int gender) {
        this.gender = gender;
    }

    /** Not-null value. */
    public java.util.Date getBirthday() {
        return birthday;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public int getMeasurementSystem() {
        return measurementSystem;
    }

    public void setMeasurementSystem(int measurementSystem) {
        this.measurementSystem = measurementSystem;
    }

    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public int getActivityFactor() {
        return activityFactor;
    }

    public void setActivityFactor(int activityFactor) {
        this.activityFactor = activityFactor;
    }

    public Double getBmr() {
        return bmr;
    }

    public void setBmr(Double bmr) {
        this.bmr = bmr;
    }

    public int getGoal() {
        return goal;
    }

    public void setGoal(int goal) {
        this.goal = goal;
    }

    public Double getMaintain() {
        return maintain;
    }

    public void setMaintain(Double maintain) {
        this.maintain = maintain;
    }

    public Double getBurn() {
        return burn;
    }

    public void setBurn(Double burn) {
        this.burn = burn;
    }

    public Double getGain() {
        return gain;
    }

    public void setGain(Double gain) {
        this.gain = gain;
    }

}
